Repository aregtech/areg-sdk-tools, pull requests merged in 2025-03, with the labels that each got.

#218 Fixed setting default values in the parameters of methods
  sources/lusan/data/common/DataTypePrimitive.cpp
  sources/lusan/data/common/DataTypePrimitive.hpp
  sources/lusan/data/common/MethodBase.cpp
  sources/lusan/data/common/MethodBase.hpp
  sources/lusan/model/si/SIMethodModel.cpp
  sources/lusan/view/si/SIMethod.cpp
  sources/lusan/view/si/SIMethodParamDetails.cpp
  sources/lusan/view/si/SIMethodParamDetails.hpp
  sources/test/10/HelloWorld.siml
  sources/test/NewVersion.siml
  sources/test/OldVersion.siml
Labels: enhancement

#220 Fixed issue with move up / down of parameter
  sources/lusan/data/common/MethodBase.cpp
  sources/lusan/data/common/MethodBase.hpp
  sources/lusan/data/common/MethodParameter.cpp
  sources/lusan/model/si/SIMethodModel.hpp
  sources/lusan/view/si/SIMethod.cpp
  sources/lusan/view/si/SIMethod.hpp
  sources/test/10/HelloWorld.siml
  sources/test/NewVersion.siml
  sources/test/OldVersion.siml
Labels: enhancement

#223 222 integrate service interface design with areg framework
  sources/lusan/data/common/ConstantEntry.cpp
  sources/lusan/data/common/FieldEntry.cpp
  sources/lusan/data/si/SIAttributeData.cpp
  sources/lusan/data/si/SIConstantData.cpp
  sources/lusan/data/si/SIDataTypeData.cpp
  sources/lusan/data/si/SIIncludeData.cpp
  sources/lusan/data/si/SIMethodBase.cpp
  sources/lusan/data/si/SIMethodBase.hpp
  sources/lusan/data/si/SIMethodBroadcast.cpp
  sources/lusan/data/si/SIMethodData.cpp
  sources/lusan/data/si/SIMethodRequest.cpp
  sources/lusan/data/si/SIMethodResponse.cpp
  sources/lusan/view/si/SIAttribute.cpp
  sources/lusan/view/si/SIConstant.cpp
  sources/lusan/view/si/SIMethod.cpp
  sources/lusan/view/si/SIMethodParamDetails.cpp
  sources/lusan/view/si/SIMethodParamDetails.hpp
Labels: bug, enhancement

#227 Navigation scroll
  sources/lusan/app/LusanApplication.cpp
  sources/lusan/app/LusanApplication.hpp
  sources/lusan/view/common/MdiMainWindow.cpp
  sources/lusan/view/common/Navigation.cpp
  sources/lusan/view/common/Navigation.hpp
  sources/lusan/view/si/ui/SIOverview.ui
Labels: bug, enhancement

#230 225 integrate log observer library
  CMakeLists.txt
  conf/cmake/common.cmake
  conf/cmake/setup.cmake
  sources/lusan/app/main.cpp
Labels: enhancement

#240 231 log observer
  CMakeLists.txt
  sources/lusan/data/CMakeLists.txt
  sources/lusan/data/log/CMakeLists.txt
  sources/lusan/data/log/LogObserver.cpp
  sources/lusan/data/log/LogObserver.hpp
Labels: enhancement, tool, logging

#241 Feature/5 application option (directory settings)
  sources/lusan/view/common/CMakeLists.txt
  sources/lusan/view/common/ProjectDirSettings.cpp
  sources/lusan/view/common/ProjectDirSettings.hpp
  sources/lusan/view/common/ProjectSettings.cpp
  sources/lusan/view/common/ProjectSettings.hpp
  sources/lusan/view/common/ui/CMakeLists.txt
  sources/lusan/view/common/ui/ProjectDirSettings.ui
  sources/lusan/view/common/ui/ProjectSettings.ui
Labels: enhancement, user interface

#243 239 log observer empty local component
  sources/lusan/data/log/CMakeLists.txt
  sources/lusan/data/log/LogObserver.cpp
  sources/lusan/data/log/LogObserver.hpp
  sources/lusan/data/log/LogObserverComp.cpp
  sources/lusan/data/log/LogObserverComp.hpp
  sources/lusan/data/log/LogObserverEvent.cpp
  sources/lusan/data/log/LogObserverEvent.hpp
  sources/lusan/data/log/NELogObserver.cpp
  sources/lusan/data/log/NELogObserver.hpp
Labels: enhancement, tool, logging

#248 246 add log viewer mdi window
  sources/lusan/data/log/LogObserver.cpp
  sources/lusan/data/log/LogObserver.hpp
  sources/lusan/data/log/LogObserverComp.cpp
  sources/lusan/data/log/LogObserverComp.hpp
  sources/lusan/model/CMakeLists.txt
  sources/lusan/model/log/CMakeLists.txt
  sources/lusan/model/log/LogViewerModel.cpp
  sources/lusan/model/log/LogViewerModel.hpp
  sources/lusan/view/common/MdiMainWindow.cpp
  sources/lusan/view/common/MdiMainWindow.hpp
  sources/lusan/view/log/CMakeLists.txt
  sources/lusan/view/log/LogViewer.cpp
  sources/lusan/view/log/LogViewer.hpp
  sources/lusan/view/log/ui/CMakeLists.txt
  sources/lusan/view/log/ui/LogViewer.ui
Labels: enhancement, tool, logging
